# Generated by Django 2.0.6 on 2018-07-02 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('solution_text', models.CharField(max_length=200)),
                ('question_type', models.CharField(choices=[('QUAD', 'Quadratic'), ('LIN', 'Linear'), ('POLY', 'Rational Polynomial')], default='QUAD', max_length=4)),
                ('created_date', models.DateTimeField(verbose_name='date created')),
            ],
        ),
    ]
